---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Generate UTF-8 locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set system locale
  copy:
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
      LANGUAGE=en_US.UTF-8
    dest: /etc/default/locale
    owner: root
    group: root
    mode: '0644'

- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    state: present

- name: Ensure hrms user has sudo access
  user:
    name: "{{ deploy_user }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    state: present

- name: Allow hrms user sudo without password
  lineinfile:
    path: /etc/sudoers.d/{{ deploy_user }}
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL"
    create: yes
    validate: 'visudo -cf %s'

- name: Configure firewall rules
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - "{{ backend_port }}"
    - "{{ frontend_port }}"
  notify: restart ufw

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Set timezone
  timezone:
    name: UTC

- name: Configure sysctl for performance
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { name: "net.core.somaxconn", value: "65535" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "65535" }
    - { name: "net.ipv4.ip_local_port_range", value: "1024 65535" }
    - { name: "net.ipv4.tcp_tw_reuse", value: "1" }

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0755'
  loop:
    - "{{ app_root }}"
    - "{{ backup_dir }}"
    - /var/log/{{ app_name }}



- name: Kill any hanging apt processes
  shell: |
    sudo pkill -f apt-get || true
    sudo pkill -f dpkg || true
    sleep 2
  ignore_errors: yes

- name: Remove apt locks if they exist
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/dpkg/lock-frontend
    - /var/lib/dpkg/lock
    - /var/cache/apt/archives/lock
  ignore_errors: yes

- name: Install Python build dependencies
  apt:
    name:
      - python3-dev
      - python3-pip
      - python3-venv
      - libpq-dev
      - libssl-dev
      - libffi-dev
    state: present
    update_cache: yes
  retries: 3
  delay: 10

- name: Install Node.js repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }} | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install pnpm globally
  npm:
    name: pnpm
    global: yes
    state: present

- name: Set up monitoring agent (if enabled)
  debug:
    msg: "Monitoring setup skipped - configure monitoring.yml if needed"
  when: enable_monitoring | default(false)