import { NextResponse } from "next/server"

// Mock candidate data (this would come from your database in a real app)
const mockCandidates = [
  {
    id: 1,
    name: "Sarah Johnson",
    jobTitle: "Senior Frontend Developer",
    stage: "Applied",
    rating: 4.5,
    lastActivity: "2h ago",
    avatar: "/placeholder.svg?height=32&width=32",
    email: "sarah.j@example.com",
    phone: "555-123-4567",
    location: "Remote",
    totalExperience: 7,
    relevantExperience: 5,
    skillExperience: [
      { skill: "React", years: 5 },
      { skill: "TypeScript", years: 4 },
      { skill: "Next.js", years: 3 },
    ],
    expectedSalary: "$120,000",
    noticePeriod: "2 weeks",
    resumeLink: "#",
    linkedinProfile: "#",
    notes: "Strong portfolio, good cultural fit.",
    interviewHistory: [],
    feedbackSummary: "",
    progress: 20,
  },
  {
    id: 2,
    name: "Michael Chen",
    jobTitle: "Product Manager",
    stage: "Screening",
    rating: 4.8,
    lastActivity: "1d ago",
    avatar: "/placeholder.svg?height=32&width=32",
    email: "michael.c@example.com",
    phone: "555-987-6543",
    location: "New York, NY",
    totalExperience: 10,
    relevantExperience: 8,
    skillExperience: [
      { skill: "Product Strategy", years: 8 },
      { skill: "Agile", years: 7 },
      { skill: "Market Research", years: 6 },
    ],
    expectedSalary: "$150,000",
    noticePeriod: "4 weeks",
    resumeLink: "#",
    linkedinProfile: "#",
    notes: "Excellent communication, strong leadership potential.",
    interviewHistory: [{ date: "2024-03-05", type: "Phone Screen", outcome: "Positive" }],
    feedbackSummary: "Passed initial screen with flying colors.",
    progress: 40,
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    jobTitle: "UX Designer",
    stage: "Interview",
    rating: 4.2,
    lastActivity: "3h ago",
    avatar: "/placeholder.svg?height=32&width=32",
    email: "emily.r@example.com",
    phone: "555-555-1212",
    location: "Remote",
    totalExperience: 6,
    relevantExperience: 6,
    skillExperience: [
      { skill: "Figma", years: 6 },
      { skill: "User Research", years: 5 },
      { skill: "Prototyping", years: 5 },
    ],
    expectedSalary: "$110,000",
    noticePeriod: "2 weeks",
    resumeLink: "#",
    linkedinProfile: "#",
    notes: "Creative portfolio, good understanding of user-centered design.",
    interviewHistory: [{ date: "2024-03-08", type: "Portfolio Review", outcome: "Positive" }],
    feedbackSummary: "Strong design skills, needs to work on presentation.",
    progress: 60,
  },
  {
    id: 4,
    name: "David Kim",
    jobTitle: "Backend Engineer",
    stage: "Offer",
    rating: 4.7,
    lastActivity: "5h ago",
    avatar: "/placeholder.svg?height=32&width=32",
    email: "david.k@example.com",
    phone: "555-333-2222",
    location: "San Francisco, CA",
    totalExperience: 8,
    relevantExperience: 7,
    skillExperience: [
      { skill: "Python", years: 7 },
      { skill: "Django", years: 6 },
      { skill: "AWS", years: 5 },
    ],
    expectedSalary: "$135,000",
    noticePeriod: "4 weeks",
    resumeLink: "#",
    linkedinProfile: "#",
    notes: "Exceptional technical skills, great cultural fit.",
    interviewHistory: [
      { date: "2024-02-28", type: "Technical", outcome: "Strong Hire" },
      { date: "2024-03-01", type: "Behavioral", outcome: "Strong Hire" },
    ],
    feedbackSummary: "Top candidate, extend offer immediately.",
    progress: 80,
  },
  {
    id: 5,
    name: "Lisa Wang",
    jobTitle: "DevOps Engineer",
    stage: "Hired",
    rating: 4.1,
    lastActivity: "1d ago",
    avatar: "/placeholder.svg?height=32&width=32",
    email: "lisa.w@example.com",
    phone: "555-777-8888",
    location: "Remote",
    totalExperience: 9,
    relevantExperience: 9,
    skillExperience: [
      { skill: "Kubernetes", years: 6 },
      { skill: "Docker", years: 7 },
      { skill: "CI/CD", years: 8 },
    ],
    expectedSalary: "$140,000",
    noticePeriod: "2 weeks",
    resumeLink: "#",
    linkedinProfile: "#",
    notes: "Deep expertise in cloud infrastructure.",
    interviewHistory: [
      { date: "2024-02-20", type: "Technical", outcome: "Hire" },
      { date: "2024-02-22", type: "Final", outcome: "Hire" },
    ],
    feedbackSummary: "Excellent fit for the role, extended offer and accepted.",
    progress: 100,
  },
  {
    id: 6,
    name: "John Doe",
    jobTitle: "Senior Frontend Developer",
    stage: "Applied",
    rating: 3.9,
    lastActivity: "5h ago",
    avatar: "/placeholder.svg?height=32&width=32",
    email: "john.d@example.com",
    phone: "555-111-2222",
    location: "London, UK",
    totalExperience: 6,
    relevantExperience: 4,
    skillExperience: [
      { skill: "Angular", years: 4 },
      { skill: "JavaScript", years: 6 },
    ],
    expectedSalary: "$100,000",
    noticePeriod: "4 weeks",
    resumeLink: "#",
    linkedinProfile: "#",
    notes: "Good experience, but less with React.",
    interviewHistory: [],
    feedbackSummary: "",
    progress: 20,
  },
]

export async function GET() {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 500))
  return NextResponse.json(mockCandidates)
}
