# Generated by Django 5.0.2 on 2025-07-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_applications', models.IntegerField(default=0)),
                ('qualified_candidates', models.IntegerField(default=0)),
                ('interviews_scheduled', models.IntegerField(default=0)),
                ('offers_extended', models.IntegerField(default=0)),
                ('hires_made', models.IntegerField(default=0)),
                ('qualification_rate', models.FloatField(default=0)),
                ('interview_to_offer_rate', models.FloatField(default=0)),
                ('offer_to_hire_rate', models.FloatField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_application', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_hire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_performances', to='accounts.organization')),
            ],
            options={
                'db_table': 'source_performances',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_jobs', models.IntegerField(default=0)),
                ('new_jobs', models.IntegerField(default=0)),
                ('closed_jobs', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('new_applications', models.IntegerField(default=0)),
                ('applications_in_review', models.IntegerField(default=0)),
                ('interviews_scheduled', models.IntegerField(default=0)),
                ('interviews_completed', models.IntegerField(default=0)),
                ('interviews_cancelled', models.IntegerField(default=0)),
                ('offers_extended', models.IntegerField(default=0)),
                ('offers_accepted', models.IntegerField(default=0)),
                ('offers_rejected', models.IntegerField(default=0)),
                ('hires_completed', models.IntegerField(default=0)),
                ('avg_time_to_fill', models.FloatField(default=0)),
                ('avg_time_to_hire', models.FloatField(default=0)),
                ('offer_acceptance_rate', models.FloatField(default=0)),
                ('cost_per_hire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='accounts.organization')),
            ],
            options={
                'db_table': 'recruitment_metrics',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
