---
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
  listen: restart postgresql

- name: reload postgresql
  systemd:
    name: postgresql
    state: reloaded
  listen: reload postgresql