---
# Environment
env_name: staging
deploy_user: deploy
deploy_group: deploy

# Application settings
app_name: recruit_platform
app_root: /opt/{{ app_name }}
app_repo: https://github.com/yourorg/recruit-platform.git
app_branch: develop

# Domain and SSL
domain_name: staging.recruit.yourdomain.com
use_ssl: true
ssl_email: admin@yourdomain.com

# Backend settings
backend_dir: "{{ app_root }}/backend"
backend_port: 8000
backend_workers: 2
django_settings_module: config.settings.staging
django_secret_key: "{{ vault_django_secret_key }}"
django_allowed_hosts:
  - "{{ domain_name }}"
  - "localhost"

# Frontend settings
frontend_dir: "{{ app_root }}/frontend"
frontend_port: 3000
frontend_instances: 1
next_public_api_url: "https://{{ domain_name }}/api"

# Database settings
db_name: recruit_staging
db_user: recruit_user
db_password: "{{ vault_db_password }}"
db_host: "{{ hostvars['staging-db1']['ansible_host'] }}"
db_port: 5432

# Redis settings
redis_host: "{{ hostvars['staging-redis1']['ansible_host'] }}"
redis_port: 6379
redis_password: "{{ vault_redis_password }}"

# Nginx settings
nginx_worker_processes: 2
nginx_worker_connections: 512
nginx_client_max_body_size: 10M

# Backup settings
backup_dir: /var/backups/{{ app_name }}
backup_retention_days: 7
backup_schedule: "0 3 * * *"

# Monitoring
enable_monitoring: false

# System packages (same as production)
system_packages:
  - git
  - curl
  - wget
  - vim
  - htop
  - build-essential
  - python3-dev
  - python3-pip
  - python3-venv
  - postgresql-client
  - redis-tools
  - nginx
  - certbot
  - python3-certbot-nginx
  - supervisor
  - ufw

# Python packages
python_packages:
  - gunicorn
  - celery
  - redis
  - psycopg2-binary

# Node.js version
nodejs_version: "20.x"