# Generated by Django 5.0.2 on 2025-07-25 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list)),
                ('rating_criteria', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_templates', to='accounts.organization')),
            ],
            options={
                'db_table': 'feedback_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Interview'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('panel', 'Panel Interview'), ('onsite', 'Onsite Interview'), ('final', 'Final Interview')], max_length=20)),
                ('round_number', models.IntegerField(default=1)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('preparation_materials', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.jobapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('interviewers', models.ManyToManyField(related_name='interviews_as_interviewer', to=settings.AUTH_USER_MODEL)),
                ('lead_interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('strong_hire', 'Strong Hire'), ('hire', 'Hire'), ('maybe', 'Maybe'), ('no_hire', 'No Hire'), ('strong_no_hire', 'Strong No Hire')], max_length=20)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('technical_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_solving_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cultural_fit_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('questions_asked', models.JSONField(blank=True, default=list)),
                ('detailed_notes', models.TextField(blank=True)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='interviews.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_feedbacks',
                'ordering': ['-submitted_at'],
                'unique_together': {('interview', 'interviewer')},
            },
        ),
    ]
