# Generated by Django 5.0.2 on 2025-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktemplate',
            name='questions',
            field=models.JSONField(default=list, help_text='List of question objects with id, text, type, options, required'),
        ),
        migrations.AddField(
            model_name='feedbacktemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='send_calendar_invite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='send_confirmation_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone-screen', 'Phone Screen'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('final-round', 'Final Round Interview'), ('cultural-fit', 'Cultural Fit Interview'), ('panel', 'Panel Interview'), ('onsite', 'Onsite Interview')], max_length=20),
        ),
    ]
