# Generated by Django 5.0.2 on 2025-07-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_feedbacktemplate_questions_feedbacktemplate_status_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.feedbacktemplate'),
        ),
        migrations.AddField(
            model_name='job',
            name='publish_company_website',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='publish_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='publish_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
    ]
