---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create Nginx configuration directory
  file:
    path: /etc/nginx/sites-available
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remove default Nginx site
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx

- name: Configure Nginx main configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Create site configuration
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  notify: restart nginx

- name: Create cache directory
  file:
    path: /var/cache/nginx/{{ app_name }}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Open HTTP port in firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Open HTTPS port in firewall
  ufw:
    rule: allow
    port: 443
    proto: tcp